name = "git-chat-assistant"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/git-chat-assistant/./target/wasm32-unknown-unknown/release/git_chat_assistant.wasm"

[[handler]]
type = "message-server"

[[handler]]
type = "runtime"

[[handler]]
type = "supervisor"

[[handler]]
type = "random"
max_bytes = 1048576
max_int = 9223372036854775807
allow_crypto_secure = false
